### PR TITLE
add digiline routing module

### PR DESCRIPTION
**Pull request by BuckarooBanzay**
this adds the `digiline_routing` mod, which brings:
* diode
* filter
* spliter

for digiline-signals

Repo: https://github.com/numberZero/digiline_routing

Merging the next day when there are no objections..
@Lejo1 thanks for testing
@S-S-X thanks for recommending

### CODE REVIEW

**Comment by S-S-X** [comment]
Dont remember anymore what I did but I'm pretty sure there was a way to crash server if you arranged some specific componets together in a weird way.

Anyway, if @Lejo1 tested it already and did something with all components then no objections but if some components were not tested then maybe more testing or disable some components at first?

Wont actually affect this PR but anyway: Opinions on heat calculation, good/bad/whatever? https://github.com/numberZero/digiline_routing/issues/9

**Comment by Lejo1** [comment]
> Dont remember anymore what I did but I'm pretty sure there was a way to crash server if you arranged some specific componets together in a weird way.

I didin't got that but the mod also seems to have managed that pretty well as sometimes the blocks drop themselves when they burn.

**Comment by S-S-X** [comment]
Now after thinking about it a while this also allows spamming a lot more digiline messages in complex networks, actually why I asked for this same mod maybe over year ago was indeed that I did not know how to optimize digiline communication.

This is not necessarily bad thing and per mapblock mesecon limits should be able to mitigate any issues but thing to remember in case there's any problems with systems using these components as this will allow buiding pretty complex systems that can spam a lot of messages as there's a lot less limits when messages can be filtered.

One thing that comes to mind is how I think mesecon limits work currently:
it will limit mapblock that originally generated messages.
How this mod changes anything then?
Simply just diodes will allow triggering devices a lot more often because natural show stopper, luac heat value, will not be able to limit larger system message rates.

**Comment by Lejo1** [comment]
> How this mod changes anything then?

You can split everything up and let only the messages through you want and luac wont burn each other instantly.
Yeah this modules also have limits but they should be(also can be) higher as they don't calculate anything.

**Comment by BuckarooBanzay** [comment]
merging, if it misbehaves i'll deal with it...

**Pull request merged**
