### PR TITLE
update homedecor and add workshop mod

### PR DESCRIPTION
**Pull request by BuckarooBanzay**
replaces #1480, #1575

### CODE REVIEW

**Comment by BuckarooBanzay** [comment]
```
2021-03-28 19:34:50: ERROR[Main]: ServerError: AsyncErr: environment_Step: Runtime error from mod 'pandorabox_integration_test' in callback environment_Step(): ...rldmods/pandorabox_integration_test/integration_test.lua:42: Node not present and not aliased: homedecor:kitchen_cabinet_half
```

**Comment by BuckarooBanzay** [comment]
```
 2021-04-01 15:58:39: ERROR[Server]: Node not present and not aliased: homedecor:kitchen_cabinet_half
2021-04-01 15:58:39: ERROR[Server]: Node not present and not aliased: homedecor:kitchen_cabinet_marble
2021-04-01 15:58:39: ERROR[Server]: Node not present and not aliased: computer:slaystation_off
2021-04-01 15:58:39: ERROR[Server]: Node not present and not aliased: homedecor:kitchen_cabinet_with_sink_locked
2021-04-01 15:58:39: ERROR[Server]: Node not present and not aliased: homedecor:kitchen_cabinet_half_locked
2021-04-01 15:58:39: ERROR[Server]: Node not present and not aliased: homedecor:kitchen_cabinet_marble_locked
2021-04-01 15:58:39: ERROR[Server]: Node not present and not aliased: homedecor:kitchen_cabinet_granite
2021-04-01 15:58:39: ERROR[Server]: Node not present and not aliased: homedecor:kitchen_cabinet
2021-04-01 15:58:39: ERROR[Server]: Node not present and not aliased: homedecor:kitchen_cabinet_with_sink
2021-04-01 15:58:39: ERROR[Server]: Node not present and not aliased: homedecor:kitchen_cabinet_steel_locked
2021-04-01 15:58:39: ERROR[Server]: Node not present and not aliased: homedecor:kitchen_cabinet_locked
2021-04-01 15:58:39: ERROR[Server]: Node not present and not aliased: homedecor:kitchen_cabinet_steel
2021-04-01 15:58:39: ERROR[Server]: Node not present and not aliased: homedecor:kitchen_cabinet_granite_locked
```

**Comment by BuckarooBanzay** [comment]
looks like there are some lbm's that convert missing nodes, the list is shorter now:
```
2021-04-15 07:04:33: ERROR[Server]: Node not present and not available in an aliase/lbm: computer:slaystation_off
2021-04-15 07:04:33: ERROR[Server]: Node not present and not available in an aliase/lbm: homedecor:kitchen_cabinet_marble_locked
2021-04-15 07:04:33: ERROR[Server]: Node not present and not available in an aliase/lbm: homedecor:kitchen_cabinet_steel_locked
2021-04-15 07:04:33: ERROR[Server]: Node not present and not available in an aliase/lbm: homedecor:kitchen_cabinet_granite_locked
```

**Comment by OgelGames** [comment]
Looks like the aliases and lbms have been fixed, but a few of the recipes are broken: https://gitlab.com/VanessaE/homedecor_modpack/-/issues/39

**Comment by OgelGames** [comment]
It's nice how fast VanessaE is 😄 

AFAIK, this is safe to merge now, I didn't find anything else broken when I tested it.

**Comment by BuckarooBanzay** [comment]
> AFAIK, this is safe to merge now, I didn't find anything else broken when I tested it.

thanks for updating/testing this :+1:

**Pull request merged**
