### PR TITLE
switch to @6r1d's atm mod with pipeworks support

### PR DESCRIPTION
**Pull request by BuckarooBanzay**
see: https://github.com/h-v-smacker/atm/pull/3

@6r1d i took the liberty to switch to your fork of the `atm` mod.
I'm guessing this is tested and error-free™ right? :wink:

### CODE REVIEW

**Comment by OgelGames** [comment]
Tested, they accept 5mg, 10mg, 50mg and 100mg notes, but not 1mg notes, which I think is caused by this: https://github.com/6r1d/atm/blob/master/nodes.lua#L19

**Comment by 6r1d** [comment]
Thanks, I'll fix that now. I am not sure we can match strings perfectly, but I'll make 1mg work.

**Comment by OgelGames** [comment]
> _please update PR to the last commit_.

Done. Looks good to merge now 👍

**Comment by BuckarooBanzay** [comment]
nice! can't wait to test that
(don't know where though, maybe a death-trap with automated atm deposit :rofl:)

**Pull request merged**
