### PR TITLE
remove digiline_routing mod

### PR DESCRIPTION
**Pull request by BuckarooBanzay**
replaced by the `digicontrol` mod
old nodes should be replaced by the new `digicontrol` nodes

fixes https://github.com/pandorabox-io/pandorabox.io/issues/553

### CODE REVIEW

**Comment by SwissalpS** [comment]
So far the new filters and diodes are working fine for me.
Since the new filters and spliters use only one node space, just replacing them will need some intervention by players to make sure circuits are connected correctly. Just adding a digiline wire automatically may cause more confusion than a missing one.

**Comment by S-S-X** [comment]
> Since the new filters and spliters use only one node space, just replacing them will need some intervention by players to make sure circuits are connected correctly. Just adding a digiline wire automatically may cause more confusion than a missing one.

Important thing here is digiline connection rules, will those change in any way if node is replaced with digiline wire?

If rules are exactly same then probably better to replace with LBM.
If rules are not exactly same then just adding a digiline wire automatically will cause more confusion than a missing one.

**Comment by OgelGames** [comment]
FYI, I've already worked out the replacement code here: https://github.com/OgelGames/digicontrol/blob/master/compatibility.lua
It should work seamlessly, but I've only tested it locally, I think @BuckarooBanzay said he was going to try it on the test server?

**Comment by BuckarooBanzay** [comment]
> I think @BuckarooBanzay said he was going to try it on the test server?

I just restored the latest snapshot on test.pandorabox.io and removed the `digiline_routing` mod, sorry for the delay :yum:

**Comment by OgelGames** [comment]
> and removed the `digiline_routing` mod

I just went on there now, and it's still there... 😕 (I even tried restarting the server)

**Comment by BuckarooBanzay** [comment]
> > and removed the `digiline_routing` mod
> 
> I just went on there now, and it's still there... confused (I even tried restarting the server)

sorry, my fault: i was testing something else and restored the meta-repository :facepalm: its removed again :+1: 

Also, if you are testing anyway: i've updated the engine to `5.4.0` with some internals changed regarding the map-saving, if you see something weird (disappearing mapblocks, stale data, etc) please let me know...

**Comment by OgelGames** [comment]
So I couldn't actually find much to check, but I did find something wrong, it seems that the `digicontrol` nodes are also effected and rotated by the LBM meant to fix the replaced nodes...

On the main server:
screenshot_20210218_002308

On the test server:
screenshot_20210218_000614

The `digiline_routing` nodes are replaced correctly, but the `digicontrol` filter and splitter are rotated. 😕

**Comment by OgelGames** [comment]
Fixed: https://github.com/OgelGames/digicontrol/commit/af87c9f370820b373fe416b7819e0744ac2a150b

**Comment by OgelGames** [comment]
I think this should be fine to merge now, unless you want to redo the testing on the test server...

**Pull request merged**
