### PR TITLE
Advtrains updates

### PR DESCRIPTION
**Pull request by S-S-X**
Add basic train pack mod and update advtrains.

@BuckarooBanzay can this be pulled to test server with latest world?

### CODE REVIEW

**Comment by S-S-X** [comment]
#1577

**Comment by S-S-X** [comment]
Tested few bugs that I've used lately to refresh server, some are fixed. I think ones that are not fixed yet also are not that easy to trigger by accident.

New train HUD is cool and looks very nice but does not give information as well as old text based HUD.

machine_parts recipe and drop override stuff works fine, no changes needed.

Most track components have recipes now which is very nice, also stuff I'd like to use that was not available at spawn shop like ks mast 😄

**Comment by BuckarooBanzay** [comment]
Done, restored from this backup:
```
ID        Time                 Host        Tags        Paths
--------------------------------------------------------------------
e43149e0  2021-04-02 02:00:02  akheron                 /mnt/snapshot
```

and switched to this branch, looks good so far (no crashes)

**Comment by S-S-X** [comment]
Added new train to world, ran through few routes manual and ATC then while running brough up onboard computer and hit "Clear ARS disable flag" and seems like this caused crash. ATC was enabled, ARS was enabled for cleared route, current route and upcoming route.
This is new feature, I suppose it is meant to clear "Disable ARS" setting after ARS for signal has been disabled and route has been manually set using onboard computer but not sure.

**Comment by S-S-X** [comment]
For me this would be good enough as everything I managed to break I was able to fix too without too much trouble.
There's new feature with bug causing crash but also old bugs that cause crashes have been fixed,

Also I think that fixing at least some old bugs that can be reproduced easily are more important to fix than pushing updates back because there's new not so easy to trigger bug. Few IMO important things with TCBs/sections have been fixed.

I've only tested some simple things and if some old routes and trains seem to work fine and they are.
Did not touch LuaATC at all while testing. Only station rails and ATC rails.

@SwissalpS might have done some things with LuaATC rails that could be tested?

**Comment by OgelGames** [comment]
> Another funny thing is that at Little Siberia I can hear Andrew's crosses hundreds nodes away probably at Minigames level crossing when train passes that crossing.

https://github.com/pandorabox-io/pandorabox.io/issues/598

`advtrains_crossing_bell.ogg` is on that list 😉

**Comment by SwissalpS** [comment]
> @SwissalpS might have done some things with LuaATC rails that could be tested?

Sorry, not much. Only started with atlatc, nothing to test with actually.

**Comment by S-S-X** [comment]
Probably good enough then... merging this to begin testing in production 😄
Shouldn't be that hard to revert if really needed.

**Pull request merged**
