### PR TITLE
Add headlamp mod

### PR DESCRIPTION
**Pull request by OgelGames**
https://content.minetest.net/packages/OgelGames/headlamp/

Resolves https://github.com/pandorabox-io/in-game/issues/122

@BuckarooBanzay @S-S-X @SwissalpS

### CODE REVIEW

**Comment by SwissalpS** [comment]
It certainly isn't overpowered. Had to charge it three times before my level 0 iron pickaxe broke.
Players are soon going to ask for mk2, mk3, mk4 using crystals instead of RE.
Keeping the max charge low, does make the powerbanks used more. +1

I like the brightness, wouldn't want that to change.
Of course, some might suggest to complicate things adding brightness levels to gain time.

LGTM :D

**Comment by OgelGames** [comment]
It was meant to last for 3 hours... not one minute... 🤦

**Comment by S-S-X** [comment]
Looks good and does its job.

Default battery life seems bit high, it could be better to start with 90 - 120 and increase it later if needed.

Note for technic plus update: with simple tools you could also directly use `technic.use_RE_charge` to make it bit simpler and reduce code footprint
```lua.diff
        -- Different code for different APIs
        if technic.plus then
                use_battery = function(stack)
-                       local charge = technic.get_RE_charge(stack)
-                       if charge <= battery_drain then
-                               stack:set_name("headlamp:headlamp_off")
-                               return false
+                       if technic.use_RE_charge(stack, battery_drain) then
+                               return true
                        end
-                       technic.set_RE_charge(stack, charge - battery_drain)
-                       return true
+                       stack:set_name("headlamp:headlamp_off")
+                       return false
                end
                base_def.max_charge = battery_life
        else
```

Changing empty battery to fully charged would be nice extra. but probably too much work to add that.

**Comment by SwissalpS** [comment]
> It was meant to last for 3 hours... not one minute... 
> 
> (can be adjusted by setting `headlamp_battery_life` btw:

Yes saw that. I tested on yesterday's master of MT and a almost current set of mods.
And using default setting.

3 IRL hours seems a bit long to me, for a light as bright as the sun on 1 RE :P

**Comment by SwissalpS** [comment]
> Default battery life seems bit high, it could be better to start with 90 - 120 and increase it later if needed.

I was thinking that 30-45 IRL minutes would be long enough to start out with. It's a lot easier to add more later than to reduce.

**Comment by BuckarooBanzay** [comment]
pretty nice mod :+1: (sorry for the delay)

**Pull request merged**
