### PR TITLE
add `mooncontroller` mod

### PR DESCRIPTION
**Pull request by BuckarooBanzay**
this PR adds the `mooncontroller` mod.

basically an enhanced version of the luacontroller with various enhancements from @cheapie.
It is currently in an mvp state and has some todos open but the main functionality is there:

Examples tab:
screenshot_20230514_193346

Help tab:
screenshot_20230514_193345

Console tab:
screenshot_20230514_193343

Ingame appearance:
screenshot_20230514_193336

Recipe:
screenshot_20230514_194144

### CODE REVIEW

**Comment by OgelGames** [comment]
Does this add any other functionality besides the terminal? It seems unnecessary to add another node (or rather 17) for only a small change in functionality. (though a useful one)

Disclaimer: My opinion may be biased by a certain half-finished project that has been sitting on my computer for months... :P

**Comment by BuckarooBanzay** [comment]
> a certain half-finished project that has been sitting on my computer for months

rickandmorty-showme

**Comment by S-S-X** [comment]
Could this replace mesecons luacontroller by overwriting it?

**Comment by SwissalpS** [comment]
Does it affect performance bandwidth to have the help and example tabs load everytime we open a mooncontroller?

I agree, let's see if we can replace rather than add.

Probably best to enforce the friendly mode too. (stop running when area is unloaded)

**Comment by SwissalpS** [comment]
> Does this add any other functionality besides the terminal?

Yes, it provides a global 'pos' so you don't need a jd to figure out where the luaC is. 
More importantly, it adds support for mods to provide libraries which can then be loaded into luaC with a 'require(libname)' call.

**Comment by BuckarooBanzay** [comment]
oh, forgot this was still open, PR's welcome :wink:
also: i'll move that mot to the `mt-mods` repo too soon(-ish)

**Pull request merged**
