### PR TITLE
Add digicontrol mod

### PR DESCRIPTION
**Pull request by OgelGames**
This PR adds the `digicontrol` mod, a replacement for the `digiline_routing` mod.

https://github.com/OgelGames/digicontrol

**Advantages over `digiline_routing`**

- All components are contained within single nodes.
- Doesn't duplicate digiline messages.
- Less overhead due to no overheating code.
- None of the other bugs `digiline_routing` has. (pandorabox-io/pandorabox.io#553)
- Additional Limiter and Tri-Splitter nodes. 

Once this is added and tested, `digiline_routing` can be removed and it's nodes will automatically be replaced.

@BuckarooBanzay @S-S-X @SwissalpS @Lejo1

### CODE REVIEW

**Comment by BuckarooBanzay** [comment]
nice  :+1: those look and "feel" better than the 2-node monsters from the routing mod :laughing: 

Adding this should be safe as long as the `digilines_routing` mod isn't removed if i'm understanding that correctly :thinking:
We can test the removal on a restore on the test-server after this is added and some circuits have been built with the new and old parts.

**Comment by OgelGames** [comment]
> Adding this should be safe as long as the `digilines_routing` mod isn't removed if i'm understanding that correctly 🤔

Correct, the aliases and LBM are only registered when `digiline_routing` doesn't exist: https://github.com/OgelGames/digicontrol/blob/master/compatibility.lua#L2

> We can test the removal on a restore on the test-server after this is added and some circuits have been built with the new and old parts.

Sounds good 👍

**Comment by SwissalpS** [comment]
great job guys. I like these a lot, they don't drop and vanish or destroy other nodes :)
Also congrats on the smooth replacement. I was excited to see my setups continue working seemlessly.

**Comment by BuckarooBanzay** [comment]
> great job guys.

@OgelGames :clap: :tada:

**Pull request merged**
